# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 688dad0ce03ad20b3bf00ec6cf824d97d9df8b7e63bdc1fc292a807170981bcb6c38fe842640df804937ecd975bea793467ecd6a2dae1ee62fc5197c5bc4bc59

test:
  secret_key_base: 68c59c46d79e78e5da87663f1aac111a6fcc8f06baa75eb8dc2093cec95f30ab6ba322e44cc3560a11cdc2fe61686a79bd431e1b0e185f31c5c1b119d4a37579

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
